version: "3"
services:
  postgres:
    restart: always
    container_name: postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/data/postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
    networks:
      - postgres
 
  pgadmin:
    restart: always
    links:
      - postgres:postgres
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    volumes:
      - ./data/pgadmin:/root/.pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    networks:
      - postgres
 
  elasticsearch:
    restart: always
    image: elasticsearch:7.8.1
    container_name: elasticsearch
    volumes:
      - ./data/elasticsearch:/var/lib/elasticsearch/data
    environment:
      discovery.type: 'single-node'
      xpack.security.enabled: 'true'
      ELASTIC_USERNAME: ${ELASTICSEARCH_USERNAME}
      ELASTIC_PASSWORD: ${ELASTICSEARCH_PASSWORD}
    network_mode: "host"

  kibana:
    restart: always
    image: kibana:7.8.1
    container_name: kibana
    environment:
      XPACK_SECURITY_ENABLED: 'true'
      ELASTICSEARCH_HOSTS: ${ELASTICSEARCH_NODE}
      ELASTICSEARCH_USERNAME: ${ELASTICSEARCH_USERNAME}
      ELASTICSEARCH_PASSWORD: ${ELASTICSEARCH_PASSWORD}
    network_mode: "host"
    
networks:
  postgres:
    driver: bridge